---
apiVersion: v1
kind: Service
metadata:
  name: stock-quant-factor
spec:
  type: ClusterIP
  selector:
    app: stock-quant-factor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
